services:
  - type: web
    name: genshop
    env: php
    buildCommand: composer install --no-dev --optimize-autoloader && npm install && npm run build
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://genshop.onrender.com
      - key: APP_KEY
        generateValue: true  # Render générera automatiquement une clé
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: ton-host-aiven
      - key: DB_PORT
        value: ton-port-aiven
      - key: DB_DATABASE
        value: defaultdb
      - key: DB_USERNAME
        value: avnadmin
      - key: DB_PASSWORD
        value: ton-mot-de-passe-aiven
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: MAIL_MAILER
        value: log