services:
  - type: web
    name: genshop
    runtime: docker
    plan: free
    region: virginia

    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:clear
      php artisan cache:clear
      php artisan route:clear
      php artisan view:clear
      npm install
      npm run build

    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT

    envVars:
      - key: APP_NAME
        value: GenShop

      - key: APP_ENV
        value: production

      - key: APP_DEBUG
        value: false

      - key: APP_KEY
        generateValue: true

      - key: APP_URL
        sync: false

      - key: DB_CONNECTION
        value: pgsql

      - key: DATABASE_URL
        fromDatabase:
          name: ecommerce-db
          property: connectionString

      - key: LOG_CHANNEL
        value: stack

      - key: LOG_LEVEL
        value: error

      - key: SESSION_DRIVER
        value: file

      - key: CACHE_STORE
        value: file

      - key: QUEUE_CONNECTION
        value: sync

      - key: FILESYSTEM_DISK
        value: local